---
  - name: restart rke2 agent service
    hosts: rke2-agents
    become_user: root
    become: true
    tasks:
      - name: Restart rke2-agent service
        ansible.builtin.systemd:
          name: rke2-agent
          state: restarted
        tags: 
          - restarted

      - name: Stop rke2-agent service
        ansible.builtin.systemd:
          name: rke2-agent
          state: stopped
        tags: 
          - stopped

      - name: Start rke2-agent service
        ansible.builtin.systemd:
          name: rke2-agent
          state: started
        tags: 
          - started
